---
##########################
# versions

ceph_version: pacific
manager_version: latest
openstack_version: wallaby

##########################
# docker

docker_configure_repository: true

##########################
# ansible

##########################
# ara

ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# netbox

netbox_enable: true
netbox_api_url: "http://{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}:8121"

##########################
# celery

celery_enable: false

flower_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: github.com
configuration_git_port: 22
# yamllint disable rule:line-length
configuration_git_public_key: FIXME
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: modzilla99/cfg-cookiecutter
configuration_git_username: git
configuration_git_version: main
