---
##########################################################
# ansible

# NOTE: Address where the node can be reached via SSH.
ansible_host: 10.0.33.5

##########################################################
# generic

# NOTE: Interface where the node can be reached via SSH.
console_interface: enp1s0

# NOTE: The internal interface for the internal communication.
management_interface: enp1s0

# NOTE: The address of the internal interface.
internal_address: 10.0.33.5

##########################################################
# netdata

netdata_host_type: server

##########################################################
# network-interfaces

# NOTE: This is the initial management interface. Further interfaces
#       must be added.

network_interfaces:
# Management Network
- device: enp1s0
  auto: true
  family: inet
  method: static
  address: 10.0.33.5
  netmask: 255.255.255.0
  gateway: 10.0.33.254
  mtu: 1500
# Public External Network (VLAN15) 
- device: enp7s0
  auto: true
  family: inet
  method: manual
  mtu: 1500
# External OpenStack Services
- device: vlan13
  method: static
  address: 10.66.13.5
  netmask: 255.255.255.0
  vlan:
    raw-device: enp1s0
# Internal OpenStack Services
- device: vlan14
  method: static
  address: 10.66.14.5
  netmask: 255.255.255.0
  vlan:
    raw-device: enp1s0
# Public External Network
- device: vlan15
  method: static
  address: 10.66.15.5
  netmask: 255.255.255.0
  vlan:
    raw-device: enp1s0
  mtu: 1500
# Tenant Network (Tunnel)
- device: vlan37
  auto: true
  method: manual
  family: inet
  vlan:
    raw-device: enp1s0
  mtu: 1500
# Frontend Storage Network
- device: vlan51
  method: static
  address: 10.66.51.5
  netmask: 255.255.255.0
  vlan:
    raw-device: enp1s0

##########################################################
# kolla

network_interface: enp1s0

api_interface: vlan14
bifrost_network_interface: enp1s0
dns_interface: vlan13
kolla_external_vip_interface: vlan13
migration_interface: vlan38
octavia_network_interface: vlan15
storage_interface: vlan51
tunnel_interface: vlan37

##########################################################
# ceph

# NOTE: Uncomment this when this node is a part of the Ceph cluster.

# monitor_address:
# radosgw_address:

# monitor_interface:
# radosgw_interface:

# NOTE: Uncomment this when this node should be a OSD node.

# devices:
#   - /dev/sdb
#   - /dev/sdc
#   - /dev/sdd
#   - /dev/sde
