---
##########################
# docker

docker_version: "5:20.10.12"

docker_user: "{{ operator_user }}"

# docker_configure_insecure_registries: true
# docker_insecure_registries:
#   - quay.io
ceph_docker_registry: quay.io
docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: quay.io

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChyR2xiOEH+UH8SedXB309VyxjAV+OOzi5Sxsk+iPnWO/gCWJ2JBmOTxEXO8EYT7b672FrytJu9CWAa/KyGLGpwh0U3BnXZZst9+eRQSj7f43u3D22RY79rBJufn4gJVhKSlPOuWhDn5RSe7j+f23g8AE7gsYxin39nNn9m+6tjoORysxmfNKGqnL4GQnTfa3qr41v8Lwuu9u3+tWhhAu4yRNJQT9q6E3ucELLEsFAY9V89I4cOgJzHDXWEXsOym+FZnG/mZMiVgRfOklAGu6UPBxkrZmmoA8tynR+gftrnJwEnJvND5hbzzbHj7BRoF47fYvkpg3Rv18YCc4H3eFKCcQMFNCR28+xvOpRZ6ivkVumx7oXTo603lWe6cMwjs0cIqIGGFBUXnkEQ4pCqteAOwZUykA+q2xU1E2SJ7XwkUUcaU85qUD1wrrnUglIQlmCs0KTBnDVqcU9vDPE9s9gQdV0iAUAkZNKaw7+/Q4GJQ0BXGM/bmNLTbtgiIg3+m4r3Q1R4liNXVl3272aYp2aNt8bzB/PHR+uBr+0t0o5MiIAcvXlYxYk5GNCgdCc2iumBgb7vlGsfPvPl4QcIG/MHd/fjKrlY/6ry6qYjiK2cm23SEX6TQ8IH6RbGJdCq/btu+Bzl5x91CjF4Jz/mOa3O71sSOAEaTyjUBXOi/Dvnw==
# yamllint enable rule:line-length

operator_authorized_keys:
  - "{{ operator_public_key }}"
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKW9mhpx888sF4LwpzFaGSvV5p8TBYxlOHHFQ28htgzQxqHxRR0hk1q0LpK/VVBT6ABdUVOv6xw/TR6fyu5TnbzJPwszNcHPpWbgDTE7/JeLL5oZ5IzIYFDpy/oIylXsrwcI46j3b5jXeX5iv5BW/WqZkKTVs3+inqZJ1X4wyGEFPYr6pdukwTdh1SuJ3Q6Jks4kkNESgk3Yq6J3dn+CSutqaQcEjtG2Y1c60LSoi2O9+PN+U0+qDGPcFCcQ38xuVwBWyOqKwupo/cE75b3EZSnJgnCazikUJN06iebP+r1YO/YfM0aaIbuwxMcovhQPO6nuQ+en/8ujg8FHWfnHHEvu2xxwQseYzblPxEww2BUSnNw6e9x/QUOuXYQUa2jbTX/9j6W1b+noBQjHH0ywIw4BtZJ1Hq+PHhVT+bbW3Qz2yKN0EdxYImfBcJT5MRuve/n8FlSchOww9FxNdvdqs0PLpM/ExZsEO/vQtDfo/+x7htc42sM2FFUIDjg0nCcsc= justin@ARCHJL
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCo/Ec7IjvI1N2Jn6oN6Y1I2bhBks39Q1dIHKUITpWYwOGkxRBCJ/8ZX6cnk30ZSmV/irl+lNWjc5sFsz/w8v8gymQPbdIZUe5ihbrZL/fFcXbQs36dZf9zLvctZ0MwtNXqHDOpXRSXoHIx7VHhWI+dG9uX4+yRMxQgUibrBIO2FwOeOE/cF3ZShl6UOKclDBMUFXeLBbFx6JgK9LmMP2DEWX8JZHXxDUQnVcwkBuGo9lM/LGywZgdyHi1onvkMRvRyU7zlaKdfXsoToGL42RByk/eNkGabn5/7Eibdv2a3BuEcaX6mzSse0gTnXjbnQDivsHixBpgQ/z+52hKF8mnOrZ/GLBPavCApWC7iSmi8jpm7XhSqLDPmQBcQVL6ULS9z16wQ8lNtXSweY2beItED6uf7Z8eqUtKZhfnN9WYfUSalEOuaAdrlgsftR4GAqrZkeuIdPQf5yAqbpX3SQXM/WViqmvU+EJ/XT4IZr4+Yt0i14HGEwP3lxRzdoSAvXIfmgDQTZc6d2496jb1xxMDDIMAYfGGhQYQQtFydbvQ8vuJR5xPUhchskRgxXdKCoLnQgx2CZl1mVkoDtveau15pqxEcZy5y5WlTMkAcwxmU5uf3gcVVESzAtkYYFbUrv4FeqarRSQesvvUgPrSjQqYZewEPxzp9+SQxOaO+RbY9EQ== justin@fedora-inspiron

##########################
# resolvconf

resolvconf_nameserver:
  - 10.0.0.1
  - 10.0.0.5
resolvconf_search: modlab.cloud

##########################
# hosts

hosts_type: template
hosts_additional_entries:
  api-int.modlab.cloud: 10.66.14.7
  api.modlab.cloud: 10.66.13.7

##########################
# common

cleanup_services_extra:
  - NetworkManager
  - iscsid
  - lxcfs
  - nscd
  - ntp

##########################
# kolla

kolla_internal_vip_address: 10.66.14.7
kolla_external_vip_address: 10.66.13.7

##########################
# serial

osism_serial_default: 100%
osism_serial:
  docker: 1

##########################
# chrony

chrony_servers:
  - ntp.modlab.cloud
chrony_allowed_subnets:
  - 127.0.0.1/32

##########################
# timezone

timezone_zone: DE

##########################
# ceph

ceph_share_directory: /share
ceph_cluster_fsid: c4ce85d5-68b1-4920-b5d4-043cc6b80864
configuration_git_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbJ7ji/l/UeYBrIfwE9l5+CwS3YHW9Zlg4EEdQ1UyNTcLJ5+sALPHcK1dxHe83XLN+LnOoCj9aN9l1rFs+OZ6W+xEgmDaeDPX8UJqOC6BZWF+SfagBJONHpslegq1srPOP/sZ1WUb85jVlRjpH5/EroKsOcfca7BnKlYsNehXlRvG6Wc8qXlVeXb492TP3BCQXa/DIpbwQD6DYOC0YCrEz9lelkmoASqXOBxBp5kvIYg8h3GwK2jDX7P8jmqz7htOnEtSE3UWtECYECkyhFZcNlfTLl3rQr0JtCRKleHacwa6+XRsr/BUWmurIr7zIiBgBtKRGIzQZxq+XaOgFhtU6OoVYB5a1Xe3ANp9h/52EJdV7n5xtgE26aW1+2vYyeH5IamYlTX/bSYcZCxC5X/VZ8tBZlm75JOk7NIkz6AluwJvrktKn7I4ahsdOKDc7pHNxnLR5/gLAaiHkkaSn8+GcsUl/PGDstv4bmYVQttQY2klZwhrGCBsF4NkwOhKu3EvYSXwyM70NFhgGc32nr6bK5X6thdtJVJ9D0KZ67j88pIDkP4gwk2Krvrs1Oe586Pori6/IAKCZ/SltH6fK6s/ytMAACgEXu2SBHK9ZHZRfYExx+S78bZ7BO4eYWNx0+6X67s+sR7OAajGQZs/D+fc9U1tCHyCIY6K72r3ug7i2Zw==
