---
##########################################################
# images

docker_registry: quay.io

##########################################################
# haproxy

kolla_internal_fqdn: api-int.modlab.cloud
kolla_external_fqdn: api.modlab.cloud

##########################################################
# openstack

# enable services
enable_cinder: "yes"
enable_cinder_backup: "yes"
enable_heat: "yes"

enable_grafana: "yes"

# disable services
enable_aodh: "no"
enable_barbican: "no"
enable_ceilometer: "no"
enable_designate: "no"
enable_gnocchi: "no"
enable_magnum: "no"
enable_octavia: "no"
enable_panko: "no"
enable_watcher: "no"

enable_etcd: "no"
enable_mongodb: "no"
enable_skydive: "no"

# generic

openstack_service_workers: 5

# profiling
enable_osprofiler: "no"

# elasticsearch

es_heap_size: "4g"

# rabbitmq

rabbitmq_server_additional_erl_args: "+S 1:1"

# horizon
horizon_backend_database: "yes"

# keystone
keystone_token_provider: "fernet"

# neutron
neutron_plugin_agent: "openvswitch"

enable_neutron_agent_ha: "yes"
enable_neutron_dvr: "no"
enable_neutron_qos: "yes"
enable_neutron_vpnaas: "no"

# nova
nova_console: novnc

# octavia
octavia_loadbalancer_topology: "ACTIVE_STANDBY"

# octavia_amp_boot_network_list: FIXME
# octavia_amp_secgroup_list: FIXME
# octavia_amp_flavor_id: FIXME

# ceilometer
ceilometer_database_type: gnocchi
ceilometer_event_type: panko

# designate
designate_ns_record: openstack.modlab.cloud

##########################################################
# external ceph

enable_ceph: "no"

cinder_backend_ceph: "yes"
glance_backend_ceph: "yes"
gnocchi_backend_storage: "ceph"
nova_backend_ceph: "yes"

ceph_gnocchi_pool_name: "metrics"
cinder_backup_driver: "ceph"
glance_backend_file: "no"

ceph_nova_user: nova
ceph_nova_keyring: ceph.client.nova.keyring

# NOTE: public_network from environments/ceph/configuration.yml
ceph_public_network: 10.66.51.10/24

##########################################################
# other
